USE [master]
GO

/****** Object:  Database [AdaTrain]    Script Date: 01/09/2017 10:53:28 AM ******/
CREATE DATABASE [AdaTrain]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdaTrain', FILENAME = N'C:\Database\AdaTrain.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AdaTrain_log', FILENAME = N'C:\Database\AdaTrain_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Thai_CI_AS
GO

ALTER DATABASE [AdaTrain] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdaTrain].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdaTrain] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdaTrain] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdaTrain] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdaTrain] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdaTrain] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdaTrain] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdaTrain] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AdaTrain] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdaTrain] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdaTrain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdaTrain] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdaTrain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdaTrain] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdaTrain] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdaTrain] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdaTrain] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdaTrain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdaTrain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdaTrain] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdaTrain] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdaTrain] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdaTrain] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdaTrain] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdaTrain] SET RECOVERY FULL 
GO

ALTER DATABASE [AdaTrain] SET  MULTI_USER 
GO

ALTER DATABASE [AdaTrain] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdaTrain] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdaTrain] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdaTrain] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdaTrain] SET  READ_WRITE 
GO

